name: "Auto Deploy PR"

concurrency: 
  group: pr-workflow-${{ github.ref }}-${{ github.event.action }}
  cancel-in-progress: true

on: 
  pull_request:
    types:
      - opened
      - reopened
      - closed
      - synchronize

env:
  SERVICE: dmm-interface

jobs:
  prepare:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-18.04
    outputs:
      head_sha: ${{ steps.head_sha.outputs.value }}
      repo_name: ${{ github.event.repository.name }}
      pr_number: ${{ steps.pr_number.outputs.value }}
      image_name: "kybernetwork/${{ env.SERVICE }}"
      image_tag: ${{ steps.get_tag.outputs.value }} 
      repo_owner: ${{ github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract branch
        shell: bash
        id: current_branch
        run: |
          if [[ ! "${{ github.ref }}"  = "refs/tags/"* ]]; then
            if [[ "${{ github.event_name }}" = "pull_request" ]]; then
              HEAD_REF=$(printf "%q" "${{ github.head_ref }}")
              HEAD_REF=${HEAD_REF/refs\/heads\//}
              BRANCH=$HEAD_REF
            else 
              REF=$(printf "%q" "${{ github.ref }}")
              REF_BRANCH=${REF/refs\/pull\//}
              REF_BRANCH=${REF_BRANCH/refs\/heads\//}
              BRANCH=$REF_BRANCH
            fi
          else 
            REF=$(printf "%q" "${{ github.ref }}")
            REF_BRANCH=${REF/refs\/tags\//}
            BRANCH=$REF_BRANCH
          fi
          echo "::set-output name=value::$BRANCH" 

      - name: Get PR Number
        id: pr_number
        run: |
          PR_NUMBER=$(echo "${{ github.ref }}" | awk 'BEGIN { FS = "/" } ; { print $3 }')
          NUMBER="${{ github.event.issue.number || github.event.number }}"
          echo "::set-output name=value::${PR_NUMBER:-$NUMBER}"

      - name: Extract GitHub HEAD SHA 
        id: head_sha 
        run: echo "::set-output name=value::${{ github.event.pull_request.head.sha }}"   

      - name: Get Docker image tag
        id: get_tag
        env:
          CURRENT_BRANCH: ${{ steps.current_branch.outputs.value }}
          HEAD_SHA: ${{ steps.head_sha.outputs.value }}
        run: |
          short_sha="$(echo "$HEAD_SHA" | head -c7)"
          branch_tag="$(echo "$CURRENT_BRANCH" | sed 's/[^a-zA-Z0-9]/-/g' | sed 's/--*/-/g' | sed 's/-$//g')"
          echo "::set-output name=value::pr-$branch_tag-$short_sha"  


  build:
    if: github.event.action != 'closed'
    needs:
      - prepare
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.SERVICE }}-buildx

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependences
        uses: bahmutov/npm-install@HEAD

      - name: Yarn Build
        env:
          CI: false 
          REACT_APP_VERSION: ${{ needs.prepare.outputs.head_sha }}
        run: yarn build-production
        
      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          labels: |
            org.label-schema.schema-version=1.0
            org.label-schema.vcs-ref=${{ needs.prepare.outputs.head_sha }}
            org.label-schema.version=${{ needs.prepare.outputs.image_tag }}
            org.label-schema.name=${{ env.SERVICE }}
          tags: |
            ${{ needs.prepare.outputs.image_name }}:${{ needs.prepare.outputs.image_tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move Docker cache 
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  on-pr-opened:
    needs:
      - prepare
      - build
    if: github.event.action == 'opened' || github.event.action == 'reopened' 
    runs-on: ubuntu-18.04
    steps:
    - name: Map event
      id: map_event
      run: |
        echo "::set-output name=value::opened"

    - name: Trigger to ADPR
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GH_PAT }}
        repository: kybernetwork/infra-config
        event-type: ${{ steps.map_event.outputs.value }}
        client-payload: ${{ toJson(needs.prepare.outputs) }}

  on-pr-closed:
    needs:
      - prepare 
    if: github.event.action == 'closed'
    runs-on: ubuntu-18.04
    steps:
    - name: Trigger to ADPR
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GH_PAT }}
        repository: kybernetwork/infra-config
        event-type: ${{ github.event.action }}
        client-payload: ${{ toJson(needs.prepare.outputs) }}
