name: 'Release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        type: string
        required: true

jobs:
  prepare:
    runs-on: ubuntu-18.04
    outputs:
      version_tag: ${{ steps.version_tag.outputs.value }}
    steps:
      - name: Format version tag
        shell: bash
        id: version_tag
        env:
          INPUT_TAG: ${{ github.event.inputs.version }}
        run: |
          TAG=${INPUT_TAG#v}
          echo "::set-output name=value::v$TAG"

  build:
    needs:
      - prepare
    runs-on: ubuntu-18.04
    env:
      SERVICE: dmm-interface
      VERSION_TAG: ${{ needs.prepare.outputs.version_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Gcloud Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCR_CREDENTIALS }}'

      - name: Setup Gcloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Configure docker
        run: gcloud auth configure-docker

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependences
        uses: bahmutov/npm-install@HEAD

      - name: Yarn Build
        env:
          CI: false
          REACT_APP_VERSION: ${{ github.sha }}
        run: yarn build

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.SERVICE }}-buildx

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          labels: |
            kyber.network.schema-version=1.0
            kyber.network.vcs-ref=${{ github.sha }}
            kyber.network.version=${{ env.VERSION_TAG }}
            kyber.network.name=${{ env.SERVICE }}
          tags: |
            asia.gcr.io/kyber-operation/core/${{ env.SERVICE }}:latest
            asia.gcr.io/kyber-operation/core/${{ env.SERVICE }}:${{ env.VERSION_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move Docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  release:
    needs:
      - prepare
      - build
    runs-on: ubuntu-18.04
    env:
      VERSION_TAG: ${{ needs.prepare.outputs.version_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Create tag
        run: |
          git tag -am $VERSION_TAG $VERSION_TAG
          git push origin "refs/tags/$VERSION_TAG"

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GH_PAT }}
          automatic_release_tag: ${{ env.VERSION_TAG }}
          prerelease: false
          title: '${{ env.VERSION_TAG }}'
